name: babylonlabs/op-finality-gadget/local-tests
on:
  pull_request:
    branches:
      - '**'
env:
  CARGO_TERM_COLOR: always
jobs:
  local-build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.86.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build contracts, check formats, and run unit tests
      run: |
        cargo fmt -- --check
        cargo test --lib
